// Column Data For Customer Table
export const columnData = [
  { name: "id", title: "Sr#" },
  { name: "name", title: "Name" },
  { name: "facilities", title: "Facilities" },
  { name: "code", title: "Code" },
  { name: "city", title: "City" },
  { name: "state", title: "State" },
  { name: "email", title: "Contact Email" },
  { name: "contactNumber", title: "Contact Number" },
  { name: "primaryContact", title: "Primary Contact" },
  { name: "customerUsers", title: "Users" },
  { name: "status", title: "Active" },
  { name: "manage", title: "Manage" },
];
// Table Extensions For Customer Table
export const tableColumnExtensions = [
  { columnName: "id", width: 70, sortingEnabled: true },
  { columnName: "name", sortingEnabled: true },
  { columnName: "facilities", title: "Facilities", sortingEnabled: false },
  { columnName: "code", sortingEnabled: true },
  { columnName: "city", sortingEnabled: true },
  { columnName: "state", sortingEnabled: false },
  { columnName: "primaryContact", width: 150, sortingEnabled: false },
  { columnName: "email", width: 220, sortingEnabled: false },
  { columnName: "contactNumber", width: 220, sortingEnabled: false },
  { columnName: "customerUsers", title: "Users", sortingEnabled: false },
  { columnName: "status", sortingEnabled: false },
  { columnName: "manage", width: 100, sortingEnabled: false },
];

//Edit Column For  Customer Table
export const editColumnData = [
  { name: "city", title: "City" },
  { name: "state", title: "State" },
  { name: "primaryContact", title: "Primary Contact" },
  { name: "email", title: "Contact Email" },
  { name: "contactNumber", title: "Contact Number" },
];

// Dummy Rows For Customer Table
export const rowData = [
  {
    id: 1,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 1,
    manage: "true",
  },
  {
    id: 2,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 3,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 4,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 1,
    manage: "true",
  },
  {
    id: 5,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 6,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 7,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 1,
    manage: "true",
  },
  {
    id: 8,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 9,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 10,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 11,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 1,
    manage: "true",
  },
  {
    id: 12,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 13,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 14,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 1,
    manage: "true",
  },
  {
    id: 15,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 16,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 17,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 18,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 19,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 20,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 21,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 22,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 23,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
  {
    id: 24,
    name: "Harry",
    code: "AFIPAK",
    city: "Baton Rogue",
    state: "Lousiana",
    primaryContact: "70815",
    email: "testing@gmail.com",
    phone: "+91-252565",
    status: 0,
    manage: "true",
  },
];

export const headerArray = [
  "Code",
  "Name",
  "Status",
  "Pick Type Shipment",
  "Pick Type Production",
  "Show Lot Number",
  "Show Lot ID1",
  "Show Lot ID2",
  "Show Bill Date",
  "Show Expiration Date",
  "Show Production Date",
  "Show Receive Date",
  "Show Unit Of Count",
  "Recurring Group Item",
  "Recurring Group Lot Number",
  "Recurring Group Lot ID1",
  "Recurring Group Lot ID2",
  "Recurring Minimum Charge",
  "City",
  "State",
  "Production Pick Logic",
  "Shipping Pick Logic",
  "Phone",
  "Email",
  "Primary Name",
];
