export const GET_USERS = 'GET_USERS';
export const SET_USERS = 'SET_USERS';
export const GET_FACILITIES = 'GET_FACILITIES';
export const SET_FACILITIES = 'SET_FACILITIES';
export const GET_SEARCHED_USER = 'GET_SEARCHED_USER';
export const GET_SEARCHED_FACILITY = 'GET_SEARCHED_FACILITY';
export const UPDATE_USER_FACILITIES = 'UPDATE_USER_FACILITIES';
export const UPDATE_FACILITY = 'UPDATE_FACILITY';
export const DELETE_FACILITY = 'DELETE_FACILITY';
export const GET_LOGIN_USER_FACILITIES = 'GET_LOGIN_USER_FACILITIES';
export const SET_LOGIN_USER_FACILITIES = 'SET_LOGIN_USER_FACILITIES';

export const GET_ROUTES = 'GET_ROUTES';
export const SET_ROUTES = 'SET_ROUTES';
export const GET_COLLAPSE = 'GET_COLLAPSE';
export const SET_COLLAPSE = 'SET_COLLAPSE';
