/**************************************** Product Not Found Table *******************************************/
// Columns Data For Product Not Received Table
export const columnData = [
  { name: "id", title: "PO#" },
  { name: "date", title: "Date" },
  { name: "customer", title: "Customer" },
  { name: "vendor", title: "Vendor" },
  { name: "shipper", title: "Shipper" },
  { name: "poAmount", title: "PO Amount" },
  { name: "partyFreight", title: "3rd Party Freight" },
  { name: "estFreight", title: "Est Freight" },
  { name: "prepaid", title: "Prepaid" },
  { name: "notes", title: "Notes" },
  { name: "manage", title: "Manage" },
];

//Edit Columns Data For Product Not Received Table
export const editColumnDataForReceivedTable = [
  { name: "vendor", title: "Vendor" },
  { name: "shipper", title: "Shipper" },
  { name: "estFreight", title: "Est Freight" },
  { name: "partyFreight", title: "3rd Party Freight" },
  { name: "prepaid", title: "Prepaid" },
  { name: "notes", title: "Notes" },
];

// Table Extensions For Product Not Received Table
export const tableColumnExtensionsForProductNotReceived = [
  { columnName: "id", width: 80, sortingEnabled: true },
  { columnName: "date", sortingEnabled: false },
  { columnName: "customer", sortingEnabled: true },
  { columnName: "vendor", sortingEnabled: false },
  { columnName: "shipper", sortingEnabled: false },
  { columnName: "poAmount", sortingEnabled: false },
  { columnName: "partyFreight", width: 160, sortingEnabled: false },
  { columnName: "estFreight", sortingEnabled: false },
  { columnName: "prepaid", sortingEnabled: false },
  { columnName: "notes", width: 400, sortingEnabled: false },
  { columnName: "manage", sortingEnabled: false },
];

// Row Data For Product Not Received Table
export const rowDataProductForNotReceived = [
  {
    id: "1",
    date: "20/05/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "",
    poAmount: "$1.00",
    partyFreight: "Reddwar Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "ddb86270fdba4bba8900e7371b089afa",
    completeItem: {
      id: "1",
      date: "20/05/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "",
      poAmount: "$1.00",
      partyFreight: "Reddwar Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "ddb86270fdba4bba8900e7371b089afa",
    },
  },
  {
    id: "2",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "2",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "3",
    date: "02/02/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "",
    poAmount: "$123.20",
    partyFreight: "",
    estFreight: "-",
    prepaid: "",
    notes: "",
    uuid: "ccb86270fdba4bba8900e7371b089aca",
    completeItem: {
      id: "3",
      date: "02/02/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "",
      poAmount: "$123.20",
      partyFreight: "",
      estFreight: "-",
      prepaid: "",
      notes: "",
      uuid: "ccb86270fdba4bba8900e7371b089aca",
    },
  },
  {
    id: "4",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "4",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "5",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "5",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "6",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "6",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "7",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "7",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "8",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "8",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "9",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "9",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "10",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "10",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "11",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "11",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "12",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "12",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
];

/**************************************** Ready To Close Table *******************************************/

// Columns Data For Ready To Close Tablee
export const editColumnDataReacyToCloseTable = [
  { name: "vendor", title: "Vendor" },
  { name: "shipper", title: "Shipper" },
  { name: "estFreight", title: "Est Freight" },
  { name: "partyFreight", title: "3rd Party Freight" },
  { name: "prepaid", title: "Prepaid" },
  { name: "notes", title: "Notes" },
];

//Table Column Extensions
export const tableColumnExtensionsForReadyToClose = [
  { columnName: "id", width: 80, sortingEnabled: true },
  { columnName: "date", sortingEnabled: false },
  { columnName: "customer", sortingEnabled: true },
  { columnName: "vendor", sortingEnabled: false },
  { columnName: "shipper", sortingEnabled: false },
  { columnName: "poAmount", sortingEnabled: false },
  { columnName: "partyFreight", width: 160, sortingEnabled: false },
  { columnName: "estFreight", sortingEnabled: false },
  { columnName: "prepaid", sortingEnabled: false },
  { columnName: "notes", width: 400, sortingEnabled: false },
  { columnName: "manage", sortingEnabled: false },
];

// Row Data For Ready To Close Table
export const rowDataReadyToClose = [
  {
    id: "1",
    date: "20/05/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "UPS Ground",
    poAmount: "$1.00",
    partyFreight: "Reddwar Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "ddb86270fdba4bba8900e7371b089afa",
    completeItem: {
      id: "1",
      date: "20/05/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "UPS Ground",
      poAmount: "$1.00",
      partyFreight: "Reddwar Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "ddb86270fdba4bba8900e7371b089afa",
    },
  },
  {
    id: "2",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "JM Swank",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "2",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "JM Swank",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "3",
    date: "02/02/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "Estes",
    poAmount: "$123.20",
    partyFreight: "",
    estFreight: "-",
    prepaid: "",
    notes: "",
    uuid: "ccb86270fdba4bba8900e7371b089aca",
    completeItem: {
      id: "3",
      date: "02/02/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "Estes",
      poAmount: "$123.20",
      partyFreight: "",
      estFreight: "-",
      prepaid: "",
      notes: "",
      uuid: "ccb86270fdba4bba8900e7371b089aca",
    },
  },
];

/**************************************** Completed PO Table ******************************************/
//Edit Columns Data For Completed PO Table
export const editColumnDataForCompletedPO = [
  { name: "vendor", title: "Vendor" },
  { name: "shipper", title: "Shipper" },
  { name: "custInvoice", title: "Cust Invoice" },
  { name: "partyFreight", title: "3rd Party Freight" },
  { name: "prepaid", title: "Prepaid" },
  { name: "notes", title: "Notes" },
];

//Table Column Extensions For Completed PO Table
export const tableColumnExtensionsForCompletedPO = [
  { columnName: "id", width: 80, sortingEnabled: true },
  { columnName: "date", sortingEnabled: false },
  { columnName: "customer", sortingEnabled: true },
  { columnName: "vendor", sortingEnabled: false },
  { columnName: "shipper", sortingEnabled: false },
  { columnName: "poAmount", sortingEnabled: false },
  { columnName: "partyFreight", width: 160, sortingEnabled: false },
  { columnName: "custInvoice", width: 130, sortingEnabled: false },
  { columnName: "prepaid", sortingEnabled: false },
  { columnName: "notes", width: 400, sortingEnabled: false },
  { columnName: "manage", sortingEnabled: false },
];
//Completed PO column data
export const columnDataCompletedPO = [
  { name: "id", title: "PO#" },
  { name: "date", title: "Date" },
  { name: "customer", title: "Customer" },
  { name: "vendor", title: "Vendor" },
  { name: "shipper", title: "Shipper" },
  { name: "poAmount", title: "PO Amount" },
  { name: "partyFreight", title: "3rd Party Freight" },
  { name: "custInvoice", title: "Cust Invoice" },
  { name: "prepaid", title: "Prepaid" },
  { name: "notes", title: "Notes" },
  { name: "manage", title: "Manage" },
];

//completed PO row data
export const rowDataCompletedPO = [
  {
    id: "1",
    date: "20/05/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "Reddaway",
    poAmount: "$1.00",
    partyFreight: "Reddwar Inc.",
    custInvoice: "SI22340201",
    prepaid: "",
    notes:
      "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "ddb86270fdba4bba8900e7371b089afa",
    completeItem: {
      id: "1",
      date: "20/05/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "Reddaway",
      poAmount: "$1.00",
      partyFreight: "Reddwar Inc.",
      custInvoice: "SI22340201",
      prepaid: "",
      notes:
        "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "ddb86270fdba4bba8900e7371b089afa",
    },
  },
  {
    id: "2",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "JM Swank",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    custInvoice: "AD12340201",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "2",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "JM Swank",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      custInvoice: "AD12340201",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "3",
    date: "02/02/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "Estes",
    poAmount: "$123.20",
    partyFreight: "",
    custInvoice: "INV00019599",
    prepaid: "",
    notes: "",
    uuid: "ccb86270fdba4bba8900e7371b089aca",
    completeItem: {
      id: "3",
      date: "02/02/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "Estes",
      poAmount: "$123.20",
      partyFreight: "",
      custInvoice: "INV00019599",
      prepaid: "",
      notes: "",
      uuid: "ccb86270fdba4bba8900e7371b089aca",
    },
  },
];

/**************************************** Closed PO Table ******************************************/
//Edit Columns Data For Closed PO Table
export const editColumnDataForClosedPO = [
  { name: "vendor", title: "Vendor" },
  { name: "shipper", title: "Shipper" },
  { name: "estFreight", title: "Est Freight" },
  { name: "partyFreight", title: "3rd Party Freight" },
  { name: "prepaid", title: "Prepaid" },
  { name: "notes", title: "Notes" },
];
//Table Column Extensions
export const tableColumnExtensionsForClosedPO = [
  { columnName: "id", width: 80, sortingEnabled: true },
  { columnName: "date", sortingEnabled: false },
  { columnName: "customer", sortingEnabled: true },
  { columnName: "vendor", sortingEnabled: false },
  { columnName: "shipper", sortingEnabled: false },
  { columnName: "poAmount", sortingEnabled: false },
  { columnName: "partyFreight", width: 160, sortingEnabled: false },
  { columnName: "estFreight", sortingEnabled: false },
  { columnName: "prepaid", sortingEnabled: false },
  { columnName: "notes", width: 400, sortingEnabled: false },
  { columnName: "manage", sortingEnabled: false },
];
// Row Data For Closed PO Table
export const rowDataClosedPO = [
  {
    id: "1",
    date: "20/05/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "UPS Ground",
    poAmount: "$1.00",
    partyFreight: "Reddwar Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "ddb86270fdba4bba8900e7371b089afa",
    completeItem: {
      id: "1",
      date: "20/05/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "UPS Ground",
      poAmount: "$1.00",
      partyFreight: "Reddwar Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Meduri Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "ddb86270fdba4bba8900e7371b089afa",
    },
  },
  {
    id: "2",
    date: "22/06/23",
    customer: "AFI Packing",
    vendor: "Smirk's",
    shipper: "JM Swank",
    poAmount: "$4,400.00",
    partyFreight: "Multiple Organics, Inc.",
    estFreight: "-",
    prepaid: "",
    notes:
      "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
    uuid: "sab86270fdba4bba8900e7371b089asa",
    completeItem: {
      id: "2",
      date: "22/06/23",
      customer: "AFI Packing",
      vendor: "Smirk's",
      shipper: "JM Swank",
      poAmount: "$4,400.00",
      partyFreight: "Multiple Organics, Inc.",
      estFreight: "-",
      prepaid: "",
      notes:
        "Alpha Berry 080281S-2S-7S cs 20 lbs each 1440 lb pallet, $1.00 per lb",
      uuid: "sab86270fdba4bba8900e7371b089asa",
    },
  },
  {
    id: "3",
    date: "02/02/23",
    customer: "AFI Packing",
    vendor: "Meduri Farms, Inc.",
    shipper: "Estes",
    poAmount: "$123.20",
    partyFreight: "",
    estFreight: "-",
    prepaid: "",
    notes: "",
    uuid: "ccb86270fdba4bba8900e7371b089aca",
    completeItem: {
      id: "3",
      date: "02/02/23",
      customer: "AFI Packing",
      vendor: "Meduri Farms, Inc.",
      shipper: "Estes",
      poAmount: "$123.20",
      partyFreight: "",
      estFreight: "-",
      prepaid: "",
      notes: "",
      uuid: "ccb86270fdba4bba8900e7371b089aca",
    },
  },
];
