// Column Names For Edite Columns Carriers
export const columnData = [
  { name: "id", title: "Sr#" },
  { name: "shipperName", title: "Shipper Name" },
  { name: "shipperCode", title: "Shipper Code" },
  { name: "address", title: "Address" },
  { name: "primaryContact", title: "Primary Contact" },
  { name: "contactEmail", title: "Contact Email" },
  { name: "contactNumber", title: "Contact Number" },
  { name: "status", title: "Status" },
  { name: "manage", title: "Manage" },
];

// Table Extensions For Carriers
export const tableColumnExtensions = [
  { columnName: "id", width: 65 },
  { columnName: "shipperName", width: 180 },
  { columnName: "shipperCode", width: 150 },
  { columnName: "address", width: 260 },
  { columnName: "primaryContact", width: 150 },
  { columnName: "contactEmail", width: 220 },
  { columnName: "contactNumber", width: 170 },
  // { columnName: "status", width: 120 },
  { columnName: "manage", sortingEnabled: false },
];

// Edit Columns For Carriers Table
export const editColumnData = [
  { name: "contactEmail", title: "Contact Email" },
  { name: "contactNumber", title: "Contact Number" },
  { name: "status", title: "Status" },
];

export const rowData = [
  {
    shipperName: "Harry",
    shipperCode: "Harry",
    address: "WDC",
    primaryContact: "BMW",
    contactEmail: "lorem@gmail.com",
    contactNumber: "252565",
    status: true,
    uuid: "adb86270fdba4bba8900e7371b089ade",
    id: 1,
  },
  {
    shipperName: "Harry",
    shipperCode: "Harry",
    address: "WDC",
    primaryContact: "BMW",
    contactNumber: "252565",
    contactEmail: "lorem@gmail.com",
    status: false,
    uuid: "adb86270fdba4dda8900e7371b089ade",
    id: 2,
  },
  {
    shipperName: "Harry",
    shipperCode: "Harry",
    address: "WDC",
    primaryContact: "BMW",
    contactNumber: "252565",
    contactEmail: "lorem@gmail.com",
    status: true,
    uuid: "adb86270fdba4aaaa8900e7371b089ade",
    id: 3,
  },
  // {
  //   id: 4,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 5,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: false,
  // },
  // {
  //   id: 6,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 7,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 8,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: false,
  // },
  // {
  //   id: 9,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 10,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: false,
  // },
  // {
  //   id: 11,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 12,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 13,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 14,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: false,
  // },
  // {
  //   id: 15,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 16,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 17,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: false,
  // },
  // {
  //   id: 18,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 19,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 20,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: false,
  // },
  // {
  //   id: 21,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 22,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: false,
  // },
  // {
  //   id: 23,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
  // {
  //   id: 24,
  //   shipperName: "Harry",
  //   shipperCode: "Harry",
  //   address: "WDC",
  //   primaryContact: "BMW",
  //   contactNumber: "252565",
  //   contactEmail: "lorem@gmail.com",
  //   status: true,
  // },
];
