export const columnData = [
  { name: "title", title: "Title" },
  { name: "description", title: "Description" },
  { name: "owner", title: "Owner" },
  { name: "lastViewed", title: "Last Viewed" },
  { name: "visibility", title: "Visibility" },
  { name: "manage", title: "Manage" },
];
export const rowData = [
  {
    title: "Need Report Name 1",
    description: "lorem adfd afikmni lajfdias sodifjdsafldsaf",
    owner: "Shane Silva",
    lastViewed: "02/02/2023, 16:50",
    visibility: "Only me",
    count: '0',
    uuid: "adb86270fdba4bba8900e7371b089ade",
    id: 1,
  },
  {
    title: "Need Report Name 2",
    description: "lorem adfd afikmni lajfdias sodifjdsafldsaf",
    owner: " Silva",
    lastViewed: "02/02/2023, 20:50",
    visibility: "Everyone",
    count: '0',
    uuid: "adb86270fdba4bba8900e7371b089ade",
    id: 2,
  },
  {
    title: "Need Report Name 3",
    description: "lorem adfd afikmni lajfdias sodifjdsafldsaf",
    owner: "James.S",
    lastViewed: "03/01/2023, 06:50",
    visibility: "Users", 
    count: '2',
    uuid: "adb86270fdba4bba8900e7371b089ade",
    id: 3,
  },
  {
    title: "Need Report Name 4",
    description: "lorem adfd afikmni lajfdias sodifjdsafldsaf",
    owner: "James.S",
    lastViewed: "03/01/2023, 06:50",
    visibility: "Everyone",
    count: '0',
    uuid: "adb86270fdba4bba8900e7371b089ade",
    id: 4,
  },
  {
    title: "Need Report Name 5",
    description: "lorem adfd afikmni lajfdias sodifjdsafldsaf",
    owner: "James.S",
    lastViewed: "03/01/2023, 06:50",
    visibility: "Facilities",
    count: '2',
    uuid: "adb86270fdba4bba8900e7371b089ade",
    id: 5,
  },
];
