export const GET_PRICING = "GET_PRICING";
export const SET_PRICING = "SET_PRICING";

//RECURRING STORAGE TYPES
export const GET_RECURRINGPRICE = "GET_RECURRINGPRICE";
export const SET_RECURRINGPRICE = "SET_RECURRINGPRICE";

//HANDLING FEES TYPES
export const GET_HANDLINGPRICE = "GET_HANDLINGPRICE";
export const SET_HANDLINGPRICE = "SET_HANDLINGPRICE";
