// All Column Widths
export const tableColumnExtensions = [
  { columnName: "id", sortingEnabled: true },
  { columnName: "name", sortingEnabled: true },
  { columnName: "phone", sortingEnabled: false },
  { columnName: "address", sortingEnabled: false },
  { columnName: "contact_name", sortingEnabled: false },
  { columnName: "contact_email", sortingEnabled: false },
  { columnName: "contact_number", sortingEnabled: false },
  { columnName: "access_level", sortingEnabled: false },
  { columnName: "last_billed", sortingEnabled: false },
  { columnName: "status", sortingEnabled: true },
  { columnName: "manage", width: 90, sortingEnabled: false },
];
// Column Names For Edit Column
export const editColumnData = [
  { name: "phone", title: "Phone" },
  { name: "address", title: "Address" },
  { name: "contact_email", title: "Contact Email" },
  { name: "contact_number", title: "Contact Number" },
  { name: "last_billed", title: "Last Billed" },
];

export const columnData = [
  { name: "id", title: "ID" },
  { name: "name", title: "Name" },
  { name: "phone", title: "Phone" },
  { name: "address", title: "Address" },
  { name: "contact_name", title: "Contact Name" },
  { name: "contact_email", title: "Contact Email" },
  { name: "contact_number", title: "Contact Number" },
  { name: "access_level", title: "Access Level" },
  { name: "last_billed", title: "Last Billed" },
  { name: "status", title: "Status" },
  { name: "manage", title: "Manage" },
];
export const rowData = [
  {
    id: 1,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'In Processing',
  },
  {
    id: 2,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'In Processing',
  },
  {
    id: 3,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'In Processing',
  },
  {
    id: 4,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'In Processing',
  },
  {
    id: 5,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'In Processing',
  },
  {
    id: 6,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 7,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 8,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 9,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 10,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 11,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 12,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 13,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 14,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 15,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 16,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 17,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 18,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 19,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 20,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 21,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 22,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Active',
  },
  {
    id: 23,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 24,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 25,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  },
  {
    id: 26,
    name: "AFI Packaging (NO QB LINK)",
    phone: "+1 (212) 410-2052",
    address: "8464 Airline Highway",
    contact_name: "Lucillie Thomson",
    contact_email: "user_email@email.com",
    contact_number: "+1 (212) 410-520",
    access_level: "Basic License",
    last_billed: "$00.00",
    status: 'Error',
  }
];

export const columnData2 = [
  { name: "sow_name", title: "SOW Name" },
  { name: "id", title: "ID" },
  { name: "billing_date", title: "Billing Date" },
  { name: "document", title: "Document" }
];

export const rowData2 = [
  { sow_name: "doc_name.pdf", id: 146, billing_date: "11/05/21", document: "doc_name.pdf" },
  { sow_name: "doc_name.pdf", id: 146, billing_date: "11/05/21", document: "doc_name.pdf" },
  { sow_name: "doc_name.pdf", id: 146, billing_date: "11/05/21", document: "doc_name.pdf" },
  { sow_name: "doc_name.pdf", id: 146, billing_date: "11/05/21", document: "doc_name.pdf" },
];

export const rowData3 = [
  { name: "11/30/21", amount: "$100.00", status: "Paid" },
  { name: "11/30/21", amount: "$100.00", status: "Paid" },
  { name: "11/30/21", amount: "$100.00", status: "Paid" },
];
