/********************************** Column Data For Products Table ********************************/
export const columnData = [
  { name: "id", title: "Inventory Id" },
  { name: "customer", title: "Customer Code" },
  { name: "category", title: "Category" },
  { name: "name", title: "Name" },
  { name: "description", title: "Description" },
  { name: "bar_code", title: "Bar Code" },
  { name: "status", title: "Active" },
  { name: "high_risk", title: "High Risk" },
  { name: "pallet_tie", title: "Pallet Tie" },
  { name: "costed", title: "Costed" },
  { name: "kit_parent_cost", title: "Kit Parent Cost" },
  { name: "allergies", title: "Allergens" },
  { name: "manage", title: "Manage" },
];

/********************************** Column Extensions For Products Table ********************************/
export const tableColumnExtensions = [
  { columnName: "id", sortingEnabled: true },
  { columnName: "customer", width: 150, sortingEnabled: true },
  { columnName: "category", sortingEnabled: true },
  { columnName: "name", sortingEnabled: true },
  { columnName: "description", sortingEnabled: false },
  { columnName: "bar_code", sortingEnabled: false },
  { columnName: "status", sortingEnabled: false },
  { columnName: "high_risk", sortingEnabled: false },
  { columnName: "pallet_tie", sortingEnabled: false },
  { columnName: "costed", sortingEnabled: false },
  { columnName: "kit_parent_cost", width: 150, sortingEnabled: false },
  { columnName: "allergies", sortingEnabled: false },
  { columnName: "manage", sortingEnabled: false },
];
/********************************** Edit Columns For Products Table ********************************/
export const editColumnData = [
  { name: "description", title: "Description" },
  { name: "bar_code", title: "Bar Code" },
  { name: "pallet_tie", title: "Pallet Tie" },
  { name: "costed", title: "Costed" },
  { name: "kit_parent_cost", title: "Kit Parent Cost" },
  { name: "allergies", title: "Allergens" },
];

export const rowData = [
  {
    id: 1,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "1538510514412",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 2,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 3,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "1538510514412",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 4,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "123 Allies Awesome Buckwheat Pancake",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 5,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 6,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 7,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "123 Lindsay's Lipsmackin Roll Out Sugar Cookie",
    bar_code: "1538510514412",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 8,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 9,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 10,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 11,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 12,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 13,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 14,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 15,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 16,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 17,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 18,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 19,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 20,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 21,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 22,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: false,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 23,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: false,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
  {
    id: 24,
    customer: "123GLU",
    category: "Finished Good",
    name: "00-000001",
    description: "Minimum invoice Up Charge",
    bar_code: "70854615",
    status: 1,
    high_risk: true,
    pallet_tie: 160,
    costed: true,
    kit_parent_cost: "9.54513131",
    allergies: "Organic",
  },
];
